FROM nginx:stable-alpine

RUN rm -rf /usr/share/nginx/html/*
COPY dist/poquer-control-03-frontend/browser/ /usr/share/nginx/html/
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]